apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats
  namespace: app
  labels:
    app: stats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats
  template:
    metadata:
      labels:
        app: stats
    spec:
      containers:
        - name: stats
          image: nuwan1998/cca-salary-submition:stats-202604261119
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: SERVER_PORT
              value: "8085"
            - name: LOG_LEVEL
              value: "ERROR"
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          resources:
            requests:
              cpu: "200m"
              memory: "384Mi"
            limits:
              cpu: "600m"
              memory: "768Mi"
          readinessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 20
