apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: app
  labels:
    app: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: nuwan1998/cca-salary-submition:vote-202604261119
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: PORT
              value: "8083"
            - name: NODE_ENV
              value: production
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "400m"
              memory: "384Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 20
